/* Generated by bin2c, do not edit manually */
#ifndef __font_ttf_h_included
#define __font_ttf_h_included

/* Contents of file font.ttf */
extern const long int font_ttf_size;
extern const unsigned char font_ttf[55452];

#endif    /* __font_ttf_h_included */
