/* Generated by bin2c, do not edit manually */
#ifndef __pointer_png_h_included
#define __pointer_png_h_included

/* Contents of file pointer.png */
extern const long int pointer_png_size;
extern const unsigned char pointer_png[150];

#endif    /* __pointer_png_h_included */
